name: church_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.4.5
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  device_preview: ^1.2.0
  dots_indicator: ^3.0.0
  firebase_auth: ^5.3.2
  firebase_core: ^3.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_facebook_auth: ^7.1.1
  flutter_native_splash: ^2.4.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.11
  flutter_svg_provider: ^1.0.7
  get_it: ^8.0.2
  go_router: ^14.3.0
  google_nav_bar: ^5.0.7
  google_sign_in: ^6.2.2
  line_icons: ^2.0.3
  modal_progress_hud_nsn: ^0.5.1
  shared_preferences: ^2.3.2

dev_dependencies:

  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
