name: church_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.4.5
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  device_preview: ^1.2.0
  dots_indicator: ^3.0.0
  firebase_auth: ^5.3.2
  firebase_core: ^3.7.0
  firebase_storage: ^12.3.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_facebook_auth: ^7.1.1
  flutter_native_splash: ^2.4.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.11
  flutter_svg_provider: ^1.0.7
  get_it: ^8.0.2
  go_router: ^14.3.0
  google_nav_bar: ^5.0.7
  google_sign_in: ^6.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  line_icons: ^2.0.3
  modal_progress_hud_nsn: ^0.5.1
  shared_preferences: ^2.3.2
  flutter_localizations:
        sdk: flutter

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:

  uses-material-design: true
  assets:
    - assets/image/icons_SVG/
    - assets/fonts/
  # example:
  fonts:
    - family: 'Cairo'
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300

flutter_assets:
  assets_path: assets/image/icons_SVG
  output_path: lib/core/constants/
  filename: images.dart
flutter_intl:
  enabled: true
