// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7v48PGV0x1swbUeyXj7plZs_RLhbVqDg',
    appId: '1:990635995503:web:51c2aaf9007c249874789a',
    messagingSenderId: '990635995503',
    projectId: 'church-8a42b',
    authDomain: 'church-8a42b.firebaseapp.com',
    storageBucket: 'church-8a42b.firebasestorage.app',
    measurementId: 'G-4LNLTFLJNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApr5qoSrVfHQ5lTdwRJj4bqCtIMvp7niQ',
    appId: '1:990635995503:android:314a6170cddbe43e74789a',
    messagingSenderId: '990635995503',
    projectId: 'church-8a42b',
    storageBucket: 'church-8a42b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4gLDlRuvvUlRYQehFzd0-Y7ByLL24L8Y',
    appId: '1:990635995503:ios:55719c9012027d4774789a',
    messagingSenderId: '990635995503',
    projectId: 'church-8a42b',
    storageBucket: 'church-8a42b.firebasestorage.app',
    iosBundleId: 'com.example.churchMobile',
  );
}
